# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Family of models for Discrete Choice
#' @description Discrete choice model: Requires data in long form.
#' For each individual (or decision maker), there are multiple observations (rows),
#' one for each of the alternatives the individual could have chosen.
#' We call the group of observations for an individual a “case”.
#' Each case represents a single statistical observation although it comprises
#' multiple observations.
#' @param formula a symbolic description of the model to be fit. An expression of the form y ~ model is interpreted as a specification that the response y is modelled by a linear predict_glmcator specified symbolically by model. A particularity for the formula is that for the case-specific variables, the user can defined an specific effect for a category.
#' @param case_id an string with the name of the column that identifies each case.
#' @param alternatives an string with the name of the column that identifies the vector of alternatives the individual could have chosen.
#' @param reference a string indicating the reference category
#' @param alternative_specific a character vector with the name of the explanatory variables that are different for each case, this are the alternative specific variables. By default, the case specific variables are the explanatory variables that are not identify in here, but that are part of the formula; in the previous example, the intercept, hinc and psize.
#' @param data a dataframe object in R, with the dependent variable as factor.
#' @param distribution an string indicating the F distribution, options are: logistic, normal, cauchit, student (any df), gompertz, gumbel.
#' @param freedom_degrees an optional scalar to indicate the degrees of freedom for the Student distribution.
#' @return Discrete_CM returns a list which can be examined with the function summary.
#' @examples
#' library(GLMcat)
#' data(TravelChoice)
#' Discrete_CM(formula = choice ~ hinc + gc + invt,
#' case_id = "indv",alternatives = "mode",reference = "air",
#' data = TravelChoice,  alternative_specific = c("gc", "invt"),
#' distribution = "logistic")
#' @note For this models it is not allowed to exclude the intercept.
#' @export
Discrete_CM <- function(formula, case_id, alternatives, reference, alternative_specific, data, distribution, freedom_degrees) {
    .Call(`_GLMcat_Discrete_CM`, formula, case_id, alternatives, reference, alternative_specific, data, distribution, freedom_degrees)
}

#' Family of models for categorical responses
#'
#' @param formula a symbolic description of the model to be fit. An expression of the form y ~ model is interpreted as a specification that the response y is modelled by a linear predict_glmcator specified symbolically by model.
#' @param ratio an string indicating the F distribution, options are: reference, adjacent, cumulative and sequential.
#' @param distribution an string indicating the F distribution, options are: logistic, normal, cauchit, student (any df), gompertz, gumbel.
#' @param categories_order a character vector indicating the incremental order of the categories: c("a", "b", "c"); a<b<c
#' @param proportional a character vector indicating the name of the variables with a proportional effect.
#' @param data a dataframe object in R, with the dependent variable as factor.
#' @param freedom_degrees an optional scalar to indicate the degrees of freedom for the Student distribution.
#' @return GLMcat returns a list which can be examined with the function summary.
#' @export
#' @examples
#' data(DisturbedDreams)
#' mod1 <- GLMcat(formula = Level ~ Age, data = DisturbedDreams,
#' distribution = "logistic",ratio = "reference")
GLMcat <- function(formula, ratio, distribution, categories_order, proportional, data, freedom_degrees) {
    .Call(`_GLMcat_GLMcat`, formula, ratio, distribution, categories_order, proportional, data, freedom_degrees)
}

#' predict_glmcation for glmcat model
#'
#' @param model_object glmcat model
#' @param data a data frame in which to look for variables with which to predict_glmcat. Note that all predict_glmcator variables should be
#' present having the same names as the variables used to fit the model.
#' @param type he type of predict_glmcations. \code{"prob"} gives probabilities,
#' \code{"cum.prob"} gives cumulative probabilities and \code{"linear.predict_glmcator"} gives
#' the linear predict_glmcator.
#' @rdname predict_glmcat
#' @export
#' @examples
#' library(GLMcat)
#' data(DisturbedDreams)
#' GLMcat(formula = Level ~ Age,
#' categories_order = c("Not.severe", "Severe.1", "Severe.2", "Very.severe"),
#' data = DisturbedDreams, distribution = "logistic")
predict_glmcat <- function(model_object, data, type) {
    .Call(`_GLMcat_predict_glmcat`, model_object, data, type)
}

#' Family of cumulative models for ordinal responses
#'
#' @param formula a symbolic description of the model to be fit. An expression of the form y ~ model is interpreted as a specification that the response y is modelled by a linear predict_glmcator specified symbolically by model.
#' @param distribution an string indicating the F distribution, options are: logistic, normal, cauchit, student (any df), gompertz, gumbel.
#' @param categories_order a character vector indicating the incremental order of the categories: c("a", "b", "c"); a<b<c
#' @param proportional a character vector indicating the name of the variables with a proportional effect.
#' @param data a dataframe object in R, with the dependent variable as factor.
#' @param freedom_degrees an optional scalar to indicate the degrees of freedom for the Student distribution.
#' @param threshold restriction to impose on the the thresholds, options are: equidistant or symmetric.
#' @param beta_init Optionl beta initialization vector.
#' @return GLMcum returns a list which can be examined with the function summary.
#' @export
#' @examples
#' data(DisturbedDreams)
#' GLMcum(formula = Level ~ Age,
#' categories_order = c("Not.severe", "Severe.1", "Severe.2", "Very.severe"),
#' data = DisturbedDreams, distribution = "logistic")
GLMcum <- function(formula, categories_order, proportional, data, distribution, freedom_degrees, beta_init, threshold) {
    .Call(`_GLMcat_GLMcum`, formula, categories_order, proportional, data, distribution, freedom_degrees, beta_init, threshold)
}

Cat_ref1 <- function(categories_order, response_categories) {
    .Call(`_GLMcat_Cat_ref1`, categories_order, response_categories)
}

